name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install depenendency
      run: npm install

    - name: node setup
      uses: actions/setup-node@v2
      
    - name: build
      run: npm run build

    - name: aws login
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: deploy
      run: aws s3 sync ./dist s3://shsong97-vue-project
