name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install depenendency
      run: npm install
      working-directory: ./my-vue


    - name: build
      run: npm run build
      working-directory: ./my-vuebuild
    
    - name: deploy s3
      env: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync \
        --region ap-northeast-2 \
        build s3://shsong97-vue-project \
        --delete
      working-directory: ./my-vuebuild
